# fly.toml app configuration file generated for route-around on 2023-07-06T20:19:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "route-around"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
